apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: source-gcp-managed-kafka-git
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://gitlab.singhritesh85.com/dexter/gcp-managed-apache-kafka.git
  ref:
    branch: main
  secretRef:
    name: gcp-managed-kafka-secret